config/routes.rb
MongodbDevise::Application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" } 
  
  root 'multiple_choice_questions#index'

  resources :users
  resources :technical_tests do
    member do
      get :report
      get :start
      patch :update_start_time
      put :update_start_time
      get :finish
      patch :update_finish
      put :update_finish
    end
  end

  resources :multiple_choice_questions do
    collection do 
      post :import
    end
  end
  

end

app/models/multiple_choice_question.rb
class MultipleChoiceQuestion
  include Mongoid::Document

  field :question, type: String
  field :right_answer, type: Integer
  field :answers, type: Array

  has_many :candidate_question

  def self.import(file)
  	spreadsheet = open_spreadsheet(file)
  	header = spreadsheet.row(1)

  	(2..spreadsheet.last_row).each do |i|
  		row_data = spreadsheet.row(i)
  		answer_values = row_data[2..8].compact
  		
  		param_keys = %w"question answers right_answer"
  		param_values = [row_data[1], answer_values, row_data.last]

  		import_params = Hash[ [param_keys, param_values].transpose ]
  		
  		multiple_choice_question = new(import_params)

  		multiple_choice_question.save!
  	end
  end

  def self.open_spreadsheet(file)
  	case File.extname(file.original_filename)
  	when ".csv" then Roo::Csv.new(file.path)
  	when ".xls" then Roo::Excel.new(file.path)
  	when ".xlsx" then Roo::Excelx.new(file.path)
  	else raise "Unknown file type: #{file.original_filename}"
  	end
  end

end

app/controllers/multiple_choice_questions_controller.rb
class MultipleChoiceQuestionsController < ApplicationController
	before_action :authenticate_user!

	def index
		@multiple_choice_questions = MultipleChoiceQuestion.all
	end

	def new

	end

	def create
		@multiple_choice_question = MultipleChoiceQuestion.new(multiple_choice_question_params)
		debugger
		@multiple_choice_question.save
		redirect_to @multiple_choice_question
	end

	def show
		@multiple_choice_question = MultipleChoiceQuestion.find(params[:id])
		@right_answer = @multiple_choice_question.right_answer + 65
		@right_answer = @right_answer.chr
	end

	def edit
		@multiple_choice_question = MultipleChoiceQuestion.find(params[:id])
	end

	def update
		@multiple_choice_question = MultipleChoiceQuestion.find(params[:id])
		@multiple_choice_question.update(multiple_choice_question_params)
		redirect_to multiple_choice_questions_path
	end

	def destroy
		@multiple_choice_question = MultipleChoiceQuestion.find(params[:id])
		@multiple_choice_question.destroy

		redirect_to multiple_choice_questions_path
	end

	def import
		MultipleChoiceQuestion.import(params[:file])
		redirect_to multiple_choice_questions_path, notice: "Products imported."
	end

	private
		def multiple_choice_question_params
			params.require(:multiple_choice_question).permit(
				:question,
				{answers: []},
				:right_answer,
			)	
		end
end

app/helpers/multiple_choice_questions_helper.rb
module MultipleChoiceQuestionsHelper
end

app/views/multiple_choice_questions/edit.html.erb
<%= content_for :cssname do %>
<%= stylesheet_link_tag "edit_multiple_choice_question", :media => "all" %>
<% end %>

<%= content_for :jsname do %>
<%= javascript_include_tag 'edit_multiple_choice_question', 'data-turbolinks-track' => true %>
<% end %>

<h1>Editing multiple choice question</h1>
<%= link_to 'Back to list of questions', multiple_choice_questions_path %>
<%= form_for :multiple_choice_question, url: multiple_choice_question_path(@multiple_choice_question), method: :patch do |f| %>
	
	<div id="question">
		<h3>Question</h3>
		<textarea name="multiple_choice_question[question]"><%= @multiple_choice_question.question%>
		</textarea>
	</div>

	<div id="answers">
		<% character = 65 %>
		<% @multiple_choice_question.answers.each do |x| %>
			<h3>Answer <%= character.chr %></h5>
			<textarea name="multiple_choice_question[answers][]"><%= x %></textarea>
			<% character += 1 %>
		<% end %>
	</div>

	<div id="add_answer">
		<button>Add another answer</button>
	</div>	

	<div id="selectbox_answer">
		<h3>Right Answer</h3>
		<% i = 0 %>
		<select name="multiple_choice_question[right_answer]">
			<% while i < @multiple_choice_question.answers.count %>
				<% if @multiple_choice_question.right_answer != i %>
					<%= ("<option value=\"" + i.to_s + "\">" + (i + 65).chr + "</option>").html_safe %>
				<% else %>
					<%= ("<option selected=\"selected\" value=\"" + i.to_s + "\">" + (i + 65).chr + "</option>").html_safe %>
				<% end %>
				<% i += 1 %>
			<% end %>
		</select>
	</div>

	<%= f.submit "Edit question" %>

<% end %>

app/views/multiple_choice_questions/index.html.erb
<%= content_for :cssname do %>
<%= stylesheet_link_tag "index_multiple_choice_question", :media => "all" %>
<% end %>

<% if notice.present? %>
	<div data-alert class="alert-box success radius">
	  <%= notice %>
	  <a href="#" class="close">&times;</a>
	</div>
<% end %>

<h1>List of all questions</h1>

<div class="panel callout radius">
	<%= link_to 'Add new question', new_multiple_choice_question_path, :class => "button success" %>
</div>

<div class="panel callout radius">
	<h3>Import Questions</h3>
	
	<%= form_tag import_multiple_choice_questions_path, multipart: true do %>
	  <%= file_field_tag :file %>
	  <%= submit_tag "Import", :class => "button" %>
	<% end %>
</div>

<table>
	<tr>
		<th>Question</th>
		<th>A</th>
		<th>B</th>
		<th>C</th>
		<th>D</th>
		<th>E</th>
		<th>F</th>
		<th>G</th>
		<th>H</th>
		<th>Right answer</th>
	</tr>

	<% @multiple_choice_questions.each do |x| %>
		<% if x.answers.present? %>
		<tr>
			<td width="276px"><%= my_render(x.question).html_safe %></td>
			<td width="144px"><%= x.answers[0] %></td>
			<td width="144px"><%= x.answers[1] %></td>
			<td width="144px"><%= x.answers[2] %></td>
			<td width="144px"><%= x.answers[3] %></td>
			<td width="144px"><%= x.answers[4] %></td>
			<td width="144px"><%= x.answers[5] %></td>
			<td width="144px"><%= x.answers[6] %></td>
			<td width="144px"><%= x.answers[7] %></td>
			<td><%= (x.right_answer + 65).chr %></td>
			<td><%= link_to 'Edit', edit_multiple_choice_question_path(x) %></td>
			<td><%= link_to 'Delete', multiple_choice_question_path(x),
				method: :delete, data: { confirm: 'Are you sure you want to delete
				this question?' } %></td>
		</tr>
		<% end %>
	<% end %>
</table>

app/views/multiple_choice_questions/new.html.erb
<%= content_for :cssname do %>
<%= stylesheet_link_tag "new_multiple_choice_question", :media => "all" %>
<% end %>

<%= content_for :jsname do %>
<%= javascript_include_tag 'new_multiple_choice_question', 'data-turbolinks-track' => true %>
<% end %>

<h1>Add new multiple choice question</h1>
<%= link_to 'Back to list of questions', multiple_choice_questions_path %>
<%= form_for :multiple_choice_question, url: multiple_choice_questions_path, method: "post" do |f| %>
	<div id="question">
		<h3>Question</h3>
		<textarea name="multiple_choice_question[question]"></textarea>
	</div>

	<div id="answers">
		<div class="answer">
			<h3>Answer A</h3>
			<textarea name="multiple_choice_question[answers][]"></textarea>
		</div>
	</div>

	<div id="add_answer">
		<button>Add another answer</button>
	</div>	

	<div id="selectbox_answer">
		<h3>Right Answer</h3>
		<select name="multiple_choice_question[right_answer]">
			<option value="0">A</option>
		</select>
	</div>
	<div class="clearfix">
		<%= f.submit "Add question", class: "button" %>
	</div>
<% end %>

app/views/multiple_choice_questions/show.html.erb
<%= content_for :cssname do %>
<%= stylesheet_link_tag "show_multiple_choice_question", :media => "all" %>
<% end %>

<%= content_for :jsname do %>
<%= javascript_include_tag 'new_multiple_choice_question', 'data-turbolinks-track' => true %>
<% end %>

<h1>Question Page</h1>
<%= link_to 'Back to list of questions', multiple_choice_questions_path %>
<div id="question">
	<h3>Quesiton</h3>
	<p><%= @multiple_choice_question.question %></p>
</div>

<div id="answers">
	<% character = 65 %>
	<% @multiple_choice_question.answers.each do |x| %>
		<h3>Answer <%= character.chr %></h3>
		<p><%= x %></p>
		<% character += 1 %>
	<% end %>
	<h3>Right Answer</h3>
	<p><%= @right_answer %></p>
</div>