config/routes.rb
MongodbDevise::Application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" } 
  
  root 'multiple_choice_questions#index'

  resources :users
  resources :technical_tests do
    member do
      get :report
      get :start
      patch :update_start_time
      put :update_start_time
      get :finish
      patch :update_finish
      put :update_finish
    end
  end

  resources :multiple_choice_questions do
    collection do 
      post :import
    end
  end
  

end

app/models/technical_test.rb
class TechnicalTest
  include Mongoid::Document

  field :name, type: String
  field :username, type: String
  field :email, type: String
  field :start_time, type: DateTime
  field :duration, type: Integer
  field :is_finish, type: Boolean

  has_many :candidate_questions, autosave: true, dependent: :delete

  def calculate_result
  	right_answer = 0
  	wrong_answer = 0

  	self.candidate_questions.each do |candidate_question|
  		if candidate_question.check_answer?
  			right_answer += 1
  		else
  			wrong_answer += 1
  		end
  	end
  	{ :right => right_answer , :wrong => wrong_answer }
  end

  def update_start_time
    self.start_time = DateTime.now
    self.save!
  end

  def update_answer(answer_index, answer_value)
    self.candidate_questions[answer_index].update_answer(answer_value)
  end

  def is_expired?
    self.duration * 3600 + self.start_time.to_i <= DateTime.now.to_i
  end

  def set_finish
    self.is_finish = true
    self.save!
  end

end

app/controllers/technical_tests_controller.rb
class TechnicalTestsController < ApplicationController
  before_action :authenticate_user!, only: [:index, :edit, :destroy, :report]
  before_action :set_technical_test, only: [:show, :edit, :update, :destroy, :start, :update_start_time, :finish, :update_finish]
  before_action :check_conditions_for_show, only: [:show]
  before_action :check_test_available, only: [:show, :start, :update_start_time]
  before_action :check_update_start_time, only: [:start, :update_start_time]
  

  # GET /technical_tests
  # GET /technical_tests.json
  def index
    @technical_tests = TechnicalTest.all
    respond_to do |format|
      format.html
    end
  end

  # GET /technical_tests/1
  # GET /technical_tests/1.json
  def show
    @question_index = technical_test_show_params[:question].to_i
    @candidate_question = @technical_test.candidate_questions[@question_index]
    @question = @candidate_question.multiple_choice_question
  end

  # GET /technical_tests/1/report
  def report
    @technical_test = TechnicalTest.find(params[:id])
    @result = @technical_test.calculate_result
  end

  # GET /technical_tests/new
  def new
    @technical_test = TechnicalTest.new
  end

  # GET /technical_tests/1/edit
  def edit
  end

  # POST /technical_tests
  # POST /technical_tests.json
  def create

    @technical_test = TechnicalTest.new(:name => technical_test_params[:name],
      :username => technical_test_params[:username],
      :email => technical_test_params[:email],
      :duration => technical_test_params[:duration])
    num_of_mcqs = technical_test_params[:num_of_mcqs].to_i
    questions = MultipleChoiceQuestion.all.shuffle.slice(0,num_of_mcqs)

    questions.each do |question|
      @technical_test.candidate_questions.build(multiple_choice_question: question)
    end

    respond_to do |format|
      if @technical_test.save
        p @technical_test
        format.html { redirect_to technical_tests_path }
        #format.html { redirect_to technical_tests_path, notice: 'Technical test was successfully created.' }
        format.json { render action: 'show', status: :created, location: @technical_test }
      else
        format.html { render action: 'new' }
        format.json { render json: @technical_test.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /technical_tests/1?question=1

  def update
    redirect_param = { :id => params_update_answer[:id], :question => params_update_answer[:question].to_i }
    respond_to do |format|
      if @technical_test.update_answer(params_update_answer[:question].to_i , params_update_answer[:selected_answer] )
        if (params_update_answer[:button_clicked] == "0")
          redirect_param[:question] -= 1
        else
          redirect_param[:question] += 1
        end
      end
      format.html { redirect_to technical_test_path redirect_param }
    end
  end

  # DELETE /technical_tests/1
  # DELETE /technical_tests/1.json
  def destroy
    @technical_test.destroy
    respond_to do |format|
      format.html { redirect_to technical_tests_url }
      format.json { head :no_content }
    end
  end


  def start
    
  end

  def update_start_time
    if params[:start_time]
      @technical_test.update_start_time  
      redirect_to technical_test_path(:id => @technical_test.id, :question => 0)
    else
      redirect_to start_technical_test_path(@technical_test)
    end 
  end

  def finish
    respond_to do |format|
      format.html
    end
  end

  def update_finish
    if params.has_key?(:question)
      @technical_test.update_answer( params[:question].to_i , params[:last_selected_answer] )
    end

    @technical_test.set_finish
    @result = @technical_test.calculate_result
    UserMailer.send_result_email("Interview Subjetc" , @technical_test.name , @technical_test.name , @result ).deliver  
    
    respond_to do |format|
      format.html { redirect_to finish_technical_test_path(@technical_test) }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_technical_test
      @technical_test = TechnicalTest.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def technical_test_params
      params[:technical_test]
    end

    def technical_test_show_params
      params.permit(:id, :question)
    end

    def params_update_answer
      params.permit(:id, :question, :button_clicked, :selected_answer)
    end

    def check_update_start_time
      if @technical_test.start_time.present?
        redirect_to technical_test_path(:id => @technical_test.id, :question => 0)
        return
      end
    end

    def check_conditions_for_show
      if @technical_test.start_time.nil?
        redirect_to start_technical_test_path(@technical_test)
        return
      end
    end

    def check_test_available
      if user_signed_in?
        redirect_to technical_tests_path
        return
      end

      if @technical_test.is_finish || (@technical_test.start_time.present? && @technical_test.is_expired?)
        redirect_to finish_technical_test_path(@technical_test)
        return
      end
    end

end

app/helpers/technical_tests_helper.rb
module TechnicalTestsHelper
	def candidate_question
		@technical_test.candidate_questions[@question_index]
	end

	

	def test_next_button 
		if @question_index < @technical_test.candidate_questions.count - 1
			button_tag("Next")
		else
			button_tag("Next", :disabled => true)
		end
	end
	def previous_next_button 
		if @question_index > 0			
			button_tag("Previous")
		else
			button_tag("Previous", :disabled => true)
		end
	end

	def test_time_remaining
    	@technical_test.duration * 3600 - DateTime.now.to_i + @technical_test.start_time.to_i
  	end
end

app/views/technical_tests/_form.html.erb
<%= form_for @technical_test, :url => {:action => @technical_test.new_record? ? :create : :update} do |f| %>
  <% if @technical_test.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@technical_test.errors.count, "error") %> prohibited this technical_test from being saved:</h2>

      <ul>
      <% @technical_test.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
    </div>
  </div>

  <div class="control-group">
    <label class="control-label" for="technical_test_num_of_mcqs">Number of multiples choice questions</label>
    <div class="controls">
      <input class="text_field" id="technical_test_num_mcq" name="technical_test[num_of_mcqs]" type="number">
    </div>
  </div>

  <div class="control-group">
    <label class="control-label">Username</label>
    <div class="controls">
      <input class="text_field" name="technical_test[username]" type="text">
    </div>
  </div>

  <div class="control-group">
    <label class="control-label">Email</label>
    <div class="controls">
      <input class="text_field" name="technical_test[email]" type="text">
    </div>
  </div>

  <div class="control-group">
    <label class="control-label">Duration (in hours)</label>
    <div class="controls">
      <input class="text_field" name="technical_test[duration]" type="text">
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'button' %>
    <%= link_to t('.cancel', :default => "Cancel"),
                technical_tests_path, :class => 'button' %>
  </div>

<% end %>

app/views/technical_tests/edit.html.erb
<h1>Editing technical_test</h1>

<%= render 'form' %>

<%= link_to 'Show', @technical_test %> |
<%= link_to 'Back', technical_tests_path %>

app/views/technical_tests/finish.html.erb
<br/>
<br/>
<h3>The test has been submitted.</h3>
<h3>Thank you for your hard work. Hope to see you soon at Misfit !!!</h3>

app/views/technical_tests/index.html.erb
<h1>Listing technical_tests</h1>

<table class="table table-bordered table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Number of questions</th>
      <th>Link to share</th>
      <th>Action</th>
    </tr>
  </thead>

  <tbody>
    <% @technical_tests.each do |technical_test| %>
      <tr>
        <td><%= technical_test.name %></td>
      
        <td><%= technical_test.candidate_questions.to_a.count %></td>
        <td> <%= technical_test_url(technical_test) %> </td>
        <td>
          <%= link_to 'Report', report_technical_test_path(technical_test) %> 
          <%= link_to 'Destroy', technical_test, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Technical test', new_technical_test_path %>

app/views/technical_tests/new.html.erb
<h1>New technical_test</h1>

<%= render 'form' %>

<%= link_to 'Back', technical_tests_path %>

app/views/technical_tests/report.html.erb
<h1>Test report</h1>

<div class="panel callout radius">
  <h3>Result</h3>
  
  <p> Right answers: <span class="label radius success"><%= @result[:right] %></span> </p>
  <p> Wrong answers: <span class="label radius alert"><%= @result[:wrong] %></span> </p>
</div>

<h3>Detail</h3>
<table class="table table-bordered table-striped">
  <thead>
    <tr>
      <th>Question</th>
      <th>Answers</th>
      <th>Right answer</th>
      <th>User answer</th>
      <th>Status</th>
    </tr>
  </thead>

  <tbody>
    <% @technical_test.candidate_questions.each do |candidate_question| %>
      <tr>
        <td><%= candidate_question.multiple_choice_question.question %></td>
        
        <td>
          <% candidate_question.multiple_choice_question.answers.each_with_index do |answer , index| %>
            <span class='answer_text'><%= index %>: <%= answer %></span>
            <br/>
          <% end %>

        </td>


        <td><%= candidate_question.multiple_choice_question.right_answer %> </td>

        <td><%= candidate_question.answer %></td>

        <td><%= candidate_question.answer == candidate_question.multiple_choice_question.right_answer %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Back', technical_tests_path, :class => "button" %>

app/views/technical_tests/show.html.erb
<%= content_for :jsname do %>
<%= javascript_include_tag 'show_technical_test', 'data-turbolinks-track' => true %>
<% end %>

<br />
<br />
<h5 id="time_remaining">Time remaining: </h5>
<%= form_for :technical_test, :html => {id: 'answer_form'}, url: technical_test_path(:id => @technical_test.id, :question => (@question_index.to_i)), method: :patch do |f| %>
	<input id="selected_answer" name="selected_answer" type="hidden" value=""/>
	<input id="button_clicked" name="button_clicked" type="hidden" value=""/>
	<div class="panel radius callout">
		<h3><%= 'Question ' + @question_index.to_s %></h3>
		<p><%= my_render @question.question %></p>
	</div>

	<div class="panel radius">
		<% @question.answers.each_with_index do |answer , index| %>
			<% if @candidate_question.answer == index %>
				<input id="radio<%= index %>" type="radio" name="selected_answer" value="<%= index %>" checked>
				<label for="radio<%= index %>"> <%= answer %> </label>
			<% else %>
				<input id="radio<%= index %>" type="radio" name="selected_answer" value="<%= index %>" >
				<label for="radio<%= index %>"> <%= answer %> </label>
			<% end %>
			<br/>
		<% end %>
	</div>

	<div id='previous_answer' class="inline-block">
		<%= previous_next_button %>
	</div>

	<div id='next_answer' class="inline-block">
		<%= test_next_button %>
	</div>

	<div id='finish_test' class="block">
		<button class="button alert">Finish</button>
	</div>
<% end %>

<%= form_for :technical_test, :html => {id: 'finish_form'}, url: update_finish_technical_test_path(:id => @technical_test.id, :question => @question_index), method: :patch do |f| %>
	<input id="last_selected_answer" name="last_selected_answer" type="hidden" value=""/>
<% end %>


<script type="text/javascript">
var idInterval;
//var time_remaining = 10;
var time_remaining = <%= test_time_remaining.to_i %>;
function updateTime() {
	var hour_remaining = parseInt(time_remaining / 3600);
	var minute_remaining = parseInt((time_remaining % 3600) / 60);
	var second_remaining = time_remaining % 60;
	document.getElementById("time_remaining").innerHTML = "Time remaining: "
	+ hour_remaining.toString() + ":" + minute_remaining.toString() + ":" + second_remaining.toString();
	time_remaining -= 1;

	if (time_remaining == -1)
	{
		var radios = document.getElementsByName('selected_answer');
		for (var i = 0, length = radios.length; i < length; i++)
			if (radios[i].checked) {
				var x = document.getElementById('last_selected_answer');
				x.value = radios[i].value;
				break;
			}
		document.getElementById('finish_form').submit();
	}
} 

$(document).ready(function() {	
	updateTime();
	clearInterval(idInterval);
	idInterval = setInterval( "updateTime()", 1000);

});


</script>

app/views/technical_tests/start.html.erb
<%= content_for :jsname do %>
<%= javascript_include_tag 'start_technical_test', 'data-turbolinks-track' => true %>
<% end %>

<br/>
<br/>
<p>Hello <%= @technical_test.username %>. This is Misfit's candidate testing site.</p>
<p>You will now have <%= @technical_test.duration %> hours to finish your test.</p>
<p>As soon as you are ready, please click the button below to start the testing round.</p>

<%= form_for :technical_test, :html => {id: 'start_form'}, url: update_start_time_technical_test_path(@technical_test), method: :patch do |f| %>
	<input id="start_time" name="start_time" type="hidden" value=""/>
	<button class="button">START</button>
<% end %>