config/routes.rb
MongodbDevise::Application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" } 
  
  root 'multiple_choice_questions#index'

  resources :users
  resources :technical_tests do
    member do
      get :report
      get :start
      patch :update_start_time
      put :update_start_time
      get :finish
      patch :update_finish
      put :update_finish
    end
  end

  resources :multiple_choice_questions do
    collection do 
      post :import
    end
  end
  

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Misfit Questions" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <nav class="top-bar" data-topbar>
      <ul class="title-area">
        <li class="name">
          <h1><a href="#">Misfit Test</a></h1>
        </li>
         <!-- Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone -->
        <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
      </ul>

      <% if user_signed_in? %>
        <section class="top-bar-section">
          <!-- Right Nav Section -->
          <ul class="right">
            <li><a href="<%= destroy_user_session_path %>" data-method="delete" rel="nofollow"><span class="label alert">Log out</span></a></li>
            <li><a href="<%= multiple_choice_questions_path %>">Questions</a></li>
            <li><a href="<%= technical_tests_path %>">Tests</a></li>
          </ul>
        </section>
      <% end %>
    </nav>

  	<div class="row">
  		<div class="large-12 columns">
    		<%= yield %>
    	</div>
	</div>
    
    <%= content_for?(:cssname) ? yield(:cssname) : "" %>
  	<%= content_for?(:jsname) ? yield(:jsname) : "" %>
  </body>
</html>